### ISSUE TITLE
Can this model be trained without the ground truth Adj matrix

### ISSUE THREAD

**Issue by SaqibMamoon** [lingbai-kong/CausalFormer#1]
Hi! 
I would like to know whether this model could be run on the timeseries data without the ground truth. I have the time series data of fMRI without the ground truth and I want to extract the causal graphs. Can it be done? Please advise.

Thanks a lot!

**Comment by lingbai-kong** [comment]
Yes, it could. You just need to set the gt as False or None here：
https://github.com/lingbai-kong/CausalFormer/blob/a2054948abec2df88d708bd0f8c574debc019f5e/interpret.py#L146-L149
And the interpreter will not evaluate the causal graph as follows:
https://github.com/lingbai-kong/CausalFormer/blob/a2054948abec2df88d708bd0f8c574debc019f5e/interpret.py#L133-L136

**Comment by SaqibMamoon** [comment]
@lingbai-kong Great!! Thanks a lot. It worked perfectly. 

My second question is, the code's outputs are attention matrix score and causal convolutional kernel score. Where in the code could I get the adjacency matrix of NxN. If possible please guide. 

Warmest Regards,

**Comment by lingbai-kong** [comment]
There isn't an explicit formulation of adjacency. However, you can rebuild the adjacency matrix from `ans`.
https://github.com/lingbai-kong/CausalFormer/blob/a2054948abec2df88d708bd0f8c574debc019f5e/interpret.py#L124-L125
