### ISSUE TITLE
Article/explanation or document relevant the code 

### ISSUE THREAD

**Issue by SaqibMamoon** [lingbai-kong/CausalFormer#2]
Hi @lingbai-kong,

I am wondering if there is any relevant document such as article or thesis explaining the structure and working of this code, which can also be cited. Please let us know if there is. 

Thanks a lot.

**Comment by lingbai-kong** [comment]
Hi @SaqibMamoon,
We upload our paper on arXiv. And the link is: https://arxiv.org/abs/2406.16708.
