### ISSUE TITLE
Training Datasets

### ISSUE THREAD

**Issue by jujingi** [lingbai-kong/CausalFormer#4]
Hello. @lingbai-kong ,

If possible, could you please provide the fMRI dataset or preprocessing code you used for training?

**Comment by stoyan-nikolov99** [comment]
[fMRI.zip](https://github.com/user-attachments/files/18181295/fMRI.zip)
I used this ones and got the same results as in the experiments.ipynb.

**Comment by jujingi** [comment]
Hello. @stoyanoronaldo 

I was able to get the same result, thanks for sharing!
