### ISSUE TITLE
missing full_window

### ISSUE THREAD

**Issue by stoyan-nikolov99** [lingbai-kong/CausalFormer#5]
Hello @lingbai-kong,

In the config_sst file in the dataloader part:

"data_loader": {
        "type": "TimeseriesDataLoader",
        "args": {
            "data_dir": "data/SST/sst.csv",
            "batch_size": 32,
            "full_window": false,
            "time_step": 32,
            "output_window": 31,
            "feature_dim": 1,
            "output_dim": 1,
            "shuffle": true,
            "validation_split": 0.1,
            "num_workers": 2
        }

The full_window variable is not present in the class TimeseriesDataLoader. If u can clarify what is this varaiable for.

Thank you.

**Comment by lingbai-kong** [comment]
Hello @stoyanoronaldo, the "full_window" was used in one of our early attempts. It is useless now. Just forget to delete.

**Comment by stoyan-nikolov99** [comment]
Ok thank you.
